name: Chroma Cluster Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - '**'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        python: ['3.8']
        platform: ['16core-64gb-ubuntu-latest']
        testfile: ["chromadb/test/db/test_system.py",
                   "chromadb/test/segment/distributed/test_memberlist_provider.py",]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install -r requirements.txt && python -m pip install -r requirements_dev.txt
    - name: Install Tilt
      run: |
        TILT_VERSION="0.33.3"
        curl -fsSL https://github.com/tilt-dev/tilt/releases/download/v$TILT_VERSION/tilt.$TILT_VERSION.linux.x86_64.tar.gz | \
          tar -xzv -C /usr/local/bin tilt
    - name: Install ctlptl
      run: |
        CTLPTL_VERSION="0.8.20"
        curl -fsSL https://github.com/tilt-dev/ctlptl/releases/download/v$CTLPTL_VERSION/ctlptl.$CTLPTL_VERSION.linux.x86_64.tar.gz | \
          tar -xzv -C /usr/local/bin ctlptl
    - name: Set up kind
      run: ctlptl create cluster kind --registry=ctlptl-registry
    - name: Start Tilt
      run: tilt ci
    - name: Integration Test
      run: bin/cluster-test.sh ${{ matrix.testfile }}

